version: "3.8"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mademe_network

  frontend:
    build: ./frontend
    ports:
<<<<<<< HEAD
      - "5173:5173"
=======
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - user-service
      - restaurant-service
      - cart-service
      - order-service
      - payment-service
      - delivery-service
      - notification-service
>>>>>>> 97ed16a13919e16662deabe550d5d5d479679256
    environment:
      - VITE_CART_SERVICE_URL=http://localhost:5002
      - VITE_ORDER_SERVICE_URL=http://localhost:5001
      - VITE_PAYMENT_SERVICE_URL=http://localhost:5003
      - VITE_RESTAURANT_SERVICE_URL=http://localhost:5005
      - VITE_USER_SERVICE_URL=http://localhost:5004
    depends_on:
      - cart-service
      - order-service
      - payment-service
<<<<<<< HEAD
      - user-service
      - restaurant-service
    networks:
      - mademe_network

  cart-service:
    build: ./cart-service
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - MONGODB_URI=mongodb://mongodb:27017/cart-service
      - BYPASS_AUTH=true
    depends_on:
      - mongodb
    networks:
      - mademe_network
=======
      - delivery-service
    environment:
      - PORT=5000
      - USER_SERVICE_URL=http://user-service:8001
      - RESTAURANT_SERVICE_URL=http://restaurant-service:8002
      - ORDER_SERVICE_URL=http://order-service:8004
      - PAYMENT_SERVICE_URL=http://payment-service:8005
      - DELIVERY_SERVICE_URL=http://delivery-service:8016
      - NOTIFICATION_SERVICE_URL=http://notification-service:8015
      - JWT_SECRET=your_jwt_secret_key_here # Change in production
      - NODE_ENV=development

  # User Service
  user-service:
    build: ./user-service
    ports:
      - "8001:8001"
    volumes:
      - ./user-service:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/user-service
      - PORT=8001
    depends_on:
      - mongodb
>>>>>>> 97ed16a13919e16662deabe550d5d5d479679256

  order-service:
    build: ./order-service
    ports:
<<<<<<< HEAD
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGODB_URI=mongodb://mongodb:27017/order-service
      - PAYMENT_SERVICE_URL=http://payment-service:5003
      - RESTAURANT_SERVICE_URL=http://restaurant-service:5005
    depends_on:
      - mongodb
    networks:
      - mademe_network

  payment-service:
    build: ./payment-service
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - MONGODB_URI=mongodb://mongodb:27017/payment-service
      - ORDER_SERVICE_URL=http://order-service:5001
    depends_on:
      - mongodb
      - order-service
    networks:
      - mademe_network

  user-service:
    build: ./user-service
    ports:
      - "5004:5004"
    environment:
      - PORT=5004
      - MONGODB_URI=mongodb://mongodb:27017/mademe-users
      - JWT_SECRET=your_jwt_secret_replace_in_production
      - JWT_EXPIRATION=24h
      - FRONTEND_URL=http://frontend:5173
    depends_on:
      - mongodb
    networks:
      - mademe_network

  restaurant-service:
    build: ./restaurant-service
    ports:
      - "5005:5005"
    environment:
      - PORT=5005
      - MONGODB_URI=mongodb://mongodb:27017/mademe-restaurants
      - JWT_SECRET=your_jwt_secret_replace_in_production
    depends_on:
      - mongodb
    networks:
      - mademe_network

networks:
  mademe_network:
    driver: bridge
=======
      - "8004:8004"
    volumes:
      - ./order-service:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/order-service
      - PORT=8004
      - NOTIFICATION_SERVICE_URL=http://notification-service:8015
      - DELIVERY_SERVICE_URL=http://delivery-service:8016
      - USER_SERVICE_URL=http://user-service:8001
      - RESTAURANT_SERVICE_URL=http://restaurant-service:8002
    depends_on:
      - mongodb
      - notification-service
      - delivery-service

  # Restaurant Service
  restaurant-service:
    build: ./restaurant-service
    ports:
      - "8002:8002"
    volumes:
      - ./restaurant-service:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/restaurant-service
      - PORT=8002
    depends_on:
      - mongodb

  # Payment Service
  payment-service:
    build: ./payment-service
    ports:
      - "8005:8005"
    volumes:
      - ./payment-service:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/payment-service
      - PORT=8005
    depends_on:
      - mongodb

  # Delivery Service
  delivery-service:
    build: ./delivery-service
    ports:
      - "8016:8016"
    volumes:
      - ./delivery-service:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/delivery-service
      - PORT=8016
      - ORDER_SERVICE_URL=http://order-service:8004
      - SECRET_KEY=delivery_service_secret
      - ALGORITHM=HS256
    depends_on:
      - mongodb

  # Cart Service
  cart-service:
    build: ./cart-service
    ports:
      - "8003:8003"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/cart-service
      - PORT=8003
    depends_on:
      - mongodb

  # Notification Service
  notification-service:
    build: ./notification-service
    ports:
      - "8015:8015"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/notification-service
      - PORT=8015
      - ORDER_SERVICE_URL=http://order-service:8004
    depends_on:
      - mongodb
>>>>>>> 97ed16a13919e16662deabe550d5d5d479679256

volumes:
  mongodb_data:
