version: "3"

services:
  # Database
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mademe
      - MONGO_INITDB_ROOT_PASSWORD=mademe_password # Change in production

  # Frontend
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api-gateway
    environment:
      - VITE_API_URL=http://localhost:5000
      - VITE_WEBSOCKET_URL=ws://localhost:5000
      - NODE_ENV=development

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "5000:5000"
    volumes:
      - ./api-gateway:/app
      - /app/node_modules
    depends_on:
      - user-service
      - restaurant-service
      - order-service
      - payment-service
      - delivery-service
    environment:
      - PORT=5000
      - USER_SERVICE_URL=http://user-service:5002
      - RESTAURANT_SERVICE_URL=http://restaurant-service:5003
      - ORDER_SERVICE_URL=http://order-service:5001
      - PAYMENT_SERVICE_URL=http://payment-service:5004
      - DELIVERY_SERVICE_URL=http://delivery-service:5005
      - JWT_SECRET=your_jwt_secret_key_here # Change in production
      - NODE_ENV=development

  # User Service
  user-service:
    build:
      context: ./user-service
    ports:
      - "5002:5002"
    volumes:
      - ./user-service:/app
      - /app/node_modules
    depends_on:
      - mongodb
    environment:
      - PORT=5002
      - MONGODB_URI=mongodb://mademe:mademe_password@mongodb:27017/mademe_users?authSource=admin
      - JWT_SECRET=your_jwt_secret_key_here # Change in production
      - NODE_ENV=development

  # Order Service
  order-service:
    build:
      context: ./order-service
    ports:
      - "5001:5001"
    volumes:
      - ./order-service:/app
      - /app/node_modules
    depends_on:
      - mongodb
    environment:
      - PORT=5001
      - MONGODB_URI=mongodb://mademe:mademe_password@mongodb:27017/mademe_orders?authSource=admin
      - NODE_ENV=development

  # Restaurant Service
  restaurant-service:
    build:
      context: ./restaurant-service
    ports:
      - "5003:5003"
    volumes:
      - ./restaurant-service:/app
      - /app/node_modules
    depends_on:
      - mongodb
    environment:
      - PORT=5003
      - MONGODB_URI=mongodb://mademe:mademe_password@mongodb:27017/mademe_restaurants?authSource=admin
      - NODE_ENV=development

  # Payment Service
  payment-service:
    build:
      context: ./payment-service
    ports:
      - "5004:5004"
    volumes:
      - ./payment-service:/app
      - /app/node_modules
    depends_on:
      - mongodb
    environment:
      - PORT=5004
      - MONGODB_URI=mongodb://mademe:mademe_password@mongodb:27017/mademe_payments?authSource=admin
      - STRIPE_SECRET_KEY=your_stripe_secret_key_here # Replace with your Stripe test key
      - NODE_ENV=development

  # Delivery Service
  delivery-service:
    build:
      context: ./delivery-service
    ports:
      - "5005:5005"
    volumes:
      - ./delivery-service:/app
      - /app/node_modules
    depends_on:
      - mongodb
    environment:
      - PORT=5005
      - MONGODB_URI=mongodb://mademe:mademe_password@mongodb:27017/mademe_delivery?authSource=admin
      - NODE_ENV=development

volumes:
  mongodb_data:
