version: "3"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mademe_network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=mademe
      - RABBITMQ_DEFAULT_PASS=mademe_password  # Change in production
    networks:
      - mademe_network

  api-gateway:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - cart-service
      - order-service
      - payment-service
      - user-service
      - restaurant-service
    networks:
      - mademe_network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_GATEWAY_URL=http://localhost:80
    depends_on:
      - api-gateway
    networks:
      - mademe_network

  cart-service:
    build: ./cart-service
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - MONGODB_URI=mongodb://mongodb:27017/cart-service
      - BYPASS_AUTH=true
      - RABBITMQ_URL=amqp://mademe:mademe_password@rabbitmq:5672
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - mademe_network

  order-service:
    build: ./order-service
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGODB_URI=mongodb://mongodb:27017/order-service
      - PAYMENT_SERVICE_URL=http://payment-service:5003
      - RESTAURANT_SERVICE_URL=http://restaurant-service:5005
      - RABBITMQ_URL=amqp://mademe:mademe_password@rabbitmq:5672
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - mademe_network

  payment-service:
    build: ./payment-service
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - MONGODB_URI=mongodb://mongodb:27017/payment-service
      - ORDER_SERVICE_URL=http://order-service:5001
      - RABBITMQ_URL=amqp://mademe:mademe_password@rabbitmq:5672
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - mademe_network

  user-service:
    build: ./user-service
    ports:
      - "5004:5004"
    environment:
      - PORT=5004
      - MONGODB_URI=mongodb://mongodb:27017/mademe-users
      - JWT_SECRET=your_jwt_secret_replace_in_production
      - JWT_EXPIRATION=24h
      - FRONTEND_URL=http://frontend:5173
      - RABBITMQ_URL=amqp://mademe:mademe_password@rabbitmq:5672
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - mademe_network

  restaurant-service:
    build: ./restaurant-service
    ports:
      - "5005:5005"
    environment:
      - PORT=5005
      - MONGODB_URI=mongodb://mongodb:27017/mademe-restaurants
      - JWT_SECRET=your_jwt_secret_replace_in_production
      - RABBITMQ_URL=amqp://mademe:mademe_password@rabbitmq:5672
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - mademe_network

networks:
  mademe_network:
    driver: bridge

volumes:
  mongodb_data:
  rabbitmq_data:
