version: "3"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mademe_network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_CART_SERVICE_URL=http://localhost:5002
      - VITE_ORDER_SERVICE_URL=http://localhost:5001
      - VITE_PAYMENT_SERVICE_URL=http://localhost:5003
      - VITE_RESTAURANT_SERVICE_URL=http://localhost:5004
      - VITE_USER_SERVICE_URL=http://localhost:5004
    depends_on:
      - cart-service
      - order-service
      - payment-service
      - user-service
    networks:
      - mademe_network

  cart-service:
    build: ./cart-service
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - MONGODB_URI=mongodb://mongodb:27017/cart-service
      - BYPASS_AUTH=true
    depends_on:
      - mongodb
    networks:
      - mademe_network

  order-service:
    build: ./order-service
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGODB_URI=mongodb://mongodb:27017/order-service
      - PAYMENT_SERVICE_URL=http://payment-service:5003
      - RESTAURANT_SERVICE_URL=http://restaurant-service:5004
    depends_on:
      - mongodb
    networks:
      - mademe_network

  payment-service:
    build: ./payment-service
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - MONGODB_URI=mongodb://mongodb:27017/payment-service
      - ORDER_SERVICE_URL=http://order-service:5001
    depends_on:
      - mongodb
      - order-service
    networks:
      - mademe_network

  user-service:
    build: ./user-service
    ports:
      - "5004:5004"
    environment:
      - PORT=5004
      - MONGODB_URI=mongodb://mongodb:27017/mademe-users
      - JWT_SECRET=your_jwt_secret_replace_in_production
      - JWT_EXPIRATION=24h
      - FRONTEND_URL=http://frontend:5173
    depends_on:
      - mongodb
    networks:
      - mademe_network

networks:
  mademe_network:
    driver: bridge

volumes:
  mongodb_data:
