version: "3.8"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  cart-service:
    build: ./cart-service
    ports:
      - "5003:5003"
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/mademe-cart?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=production
    depends_on:
      - mongodb

  order-service:
    build: ./order-service
    ports:
      - "5001:5001"
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/mademe-orders?authSource=admin
      - CART_SERVICE_URL=http://cart-service:5003
      - PAYMENT_SERVICE_URL=http://payment-service:5002
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=production
    depends_on:
      - mongodb
      - cart-service

  payment-service:
    build: ./payment-service
    ports:
      - "5002:5002"
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/mademe-payments?authSource=admin
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - ORDER_SERVICE_URL=http://order-service:5001
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=production
    depends_on:
      - mongodb
      - order-service

volumes:
  mongodb_data:
