apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: mademe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
      - name: cart-service
        image: mademe/cart-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5002
        env:
        - name: PORT
          value: "5002"
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/cart-service"
        - name: BYPASS_AUTH
          value: "true"
        resources:
          limits:
            memory: "256Mi"
            cpu: "300m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /health
            port: 5002
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5002
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: mademe
spec:
  selector:
    app: cart-service
  ports:
  - port: 5002
    targetPort: 5002
  type: ClusterIP