apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: mademe
data:
  VITE_CART_SERVICE_URL: "http://mademe.example.com/api/cart"
  VITE_ORDER_SERVICE_URL: "http://mademe.example.com/api/orders"
  VITE_PAYMENT_SERVICE_URL: "http://mademe.example.com/api/payments"
  VITE_RESTAURANT_SERVICE_URL: "http://mademe.example.com/api/restaurants"
  VITE_USER_SERVICE_URL: "http://mademe.example.com/api/users"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mademe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: mademe/frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5173
          envFrom:
            - configMapRef:
                name: frontend-config
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
            requests:
              memory: "128Mi"
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: /
              port: 5173
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 5173
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: mademe
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 5173
  type: ClusterIP
