apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: mademe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: mademe/order-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
          env:
            - name: PORT
              value: "5001"
            - name: MONGODB_URI
              value: "mongodb://mongodb:27017/order-service"
            - name: PAYMENT_SERVICE_URL
              value: "http://payment-service:5003"
            - name: RESTAURANT_SERVICE_URL
              value: "http://restaurant-service:5005"
          resources:
            limits:
              memory: "256Mi"
              cpu: "300m"
            requests:
              memory: "128Mi"
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: mademe
spec:
  selector:
    app: order-service
  ports:
    - port: 5001
      targetPort: 5001
  type: ClusterIP
