apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: mademe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: mademe/payment-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5003
          env:
            - name: PORT
              value: "5003"
            - name: MONGODB_URI
              value: "mongodb://mongodb:27017/payment-service"
            - name: ORDER_SERVICE_URL
              value: "http://order-service:5001"
          resources:
            limits:
              memory: "256Mi"
              cpu: "300m"
            requests:
              memory: "128Mi"
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: /health
              port: 5003
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 5003
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: logs-volume
              mountPath: /app/logs
      volumes:
        - name: logs-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: mademe
spec:
  selector:
    app: payment-service
  ports:
    - port: 5003
      targetPort: 5003
  type: ClusterIP
