apiVersion: v1
kind: Secret
metadata:
  name: restaurant-service-secrets
  namespace: mademe
type: Opaque
data:
  jwt-secret: eW91cl9qd3Rfc2VjcmV0X3JlcGxhY2VfaW5fcHJvZHVjdGlvbg== # Base64 encoded "your_jwt_secret_replace_in_production"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
  namespace: mademe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
      - name: restaurant-service
        image: mademe/restaurant-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5005
        env:
        - name: PORT
          value: "5005"
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/mademe-restaurants"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: restaurant-service-secrets
              key: jwt-secret
        resources:
          limits:
            memory: "256Mi"
            cpu: "300m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /health
            port: 5005
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5005
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  namespace: mademe
spec:
  selector:
    app: restaurant-service
  ports:
  - port: 5005
    targetPort: 5005
  type: ClusterIP