apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: mademe
  MONGO_INITDB_ROOT_PASSWORD: mademe_password # Change in production
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
stringData:
  JWT_SECRET: your_jwt_secret_key_here # Change in production
---
apiVersion: v1
kind: Secret
metadata:
  name: payment-secrets
type: Opaque
stringData:
  STRIPE_SECRET_KEY: your_stripe_secret_key_here # Replace with your Stripe test key
