apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
  namespace: mademe
type: Opaque
data:
  jwt-secret: eW91cl9qd3Rfc2VjcmV0X3JlcGxhY2VfaW5fcHJvZHVjdGlvbg== # Base64 encoded "your_jwt_secret_replace_in_production"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: mademe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: mademe/user-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5004
        env:
        - name: PORT
          value: "5004"
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/mademe-users"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: jwt-secret
        - name: JWT_EXPIRATION
          value: "24h"
        - name: FRONTEND_URL
          value: "http://frontend-service:5173"
        resources:
          limits:
            memory: "256Mi"
            cpu: "300m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /health
            port: 5004
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5004
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: mademe
spec:
  selector:
    app: user-service
  ports:
  - port: 5004
    targetPort: 5004
  type: ClusterIP